projects:
  medicare:
    schemaPath: amplify/backend/api/medicare/build/schema.graphql
    includes:
      - src/app/amazon/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/amazon/auto/API.generated.ts
        docsFilePath: src/graphql
        region: eu-central-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
